// SPDX-License-Identifier: MIT

//! Shell completion scripts — statically maintained under
//! `src/completions/` (previously generated by clap_complete). Keep them in
//! sync with `src/cli.rs` when the surface changes.

use crate::cli::CompletionShell;
use crate::err::Result;

const BASH: &str = include_str!("completions/idlescreen");
const ZSH: &str = include_str!("completions/_idlescreen");
const FISH: &str = include_str!("completions/idlescreen.fish");
const POWERSHELL: &str = include_str!("completions/_idlescreen.ps1");
const ELVISH: &str = include_str!("completions/idlescreen.elv");
const NUSHELL: &str = include_str!("completions/idle.nu");

pub fn handle_completion(shell: CompletionShell) -> Result<()> {
    let script = match shell {
        CompletionShell::Bash => BASH,
        CompletionShell::Zsh => ZSH,
        CompletionShell::Fish => FISH,
        CompletionShell::PowerShell => POWERSHELL,
        CompletionShell::Elvish => ELVISH,
        CompletionShell::Nushell => NUSHELL,
    };
    print!("{script}");
    Ok(())
}
